# React Native 기본 스크립트 로드
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb",{paths:[process.argv[1]]})', __dir__]).strip

platform :ios, '17.0'

prepare_react_native_project!

target 'DongnaeHankki' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'NMapsMap'      

  post_install do |installer|
    react_native_post_install(installer)
  end
end
